### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by r0x0d**

### CODE REVIEW

**Comment by TomasTomecek** [comment]
/packit build
o_O never mind then

**Comment by r0x0d** [comment]
@TomasTomecek still same error :(

**Comment by TomasTomecek** [comment]
@r0x0d also this is happening: https://status.testing-farm.io/issues/2022-10-10-redhat-ranch/

**Comment by r0x0d** [comment]
> @r0x0d also this is happening: https://status.testing-farm.io/issues/2022-10-10-redhat-ranch/

Yeah, I saw that... I will wait a bit more to continue my work on this, but the problem that I'm seeing regarding the compose not being available may be associated with that? 

Because I saw that happening since last week...

**Comment by r0x0d** [comment]
Closing this since it seems that the build is stuck

**Pull request closed without merging**
